# semantics_dict = {'living_room': 1,
#                   'kitchen': 2,
#                   'bedroom': 3,
#                   'bathroom': 4,
#                   'restroom': 5,
#                   'balcony': 6,
#                   'closet': 7,
#                   'corridor': 8,
#                   'washing_room': 9,
#                   'PS': 10,
#                   'outside': 11,
#                   'wall': 12,
#                   'no_type': 0}
# semantics_dict_rev = {0: 'no_type', 1: 'living_room', 2: 'kitchen', 3: 'bedroom',
#                       4: 'bathroom', 5: 'restroom', 6: 'balcony', 7: 'closet',
#                       8: 'corridor', 9: 'washing_room', 10: 'PS', 11: 'outside',
#                       12: 'wall'}
# semantics_dict_color = {'living_room': (0, 0, 220),
#                   'kitchen': (0, 220, 220),
#                   'bedroom': (0, 220, 0),
#                   'bathroom': (220, 220, 0),
#                   'restroom': (220, 0, 0),
#                   'balcony': (220, 0, 220),
#                   'closet': (110, 0, 110),
#                   'corridor': (110, 0, 0),
#                   'washing_room': (0, 0, 110),
#                   'PS': (0, 110, 110),
#                   'outside': (0, 0, 0),
#                   'wall': (110, 110, 110),
#                   'no_type': (20, 20, 20)}


semantics_dict = {
    'openOffice': 1,
    'elevatorRoom': 2,
    'technicalRoom': 3,
    'openCommon': 4,
    'stairway': 5,
    'workRoom': 6,
    'openSocial': 7,
    'bathRoom': 8,
    'circulationArea': 9,
    'storageRoom': 10,
    'printerRoom': 11,
    'meetRoom': 12,
    'noRoom': 13,
    'none': 14,
    'kitchen': 15,
    'wardrobeRoom': 16,
    'quietRoom': 17,
    'custom': 18
}

semantics_dict_rev = {v: k for k, v in semantics_dict.items()}

semantics_dict_color = {
    'openOffice': (255, 0, 0),
    'elevatorRoom': (0, 255, 0),
    'technicalRoom': (0, 0, 255),
    'openCommon': (255, 255, 0),
    'stairway': (255, 0, 255),
    'workRoom': (0, 255, 255),
    'openSocial': (128, 0, 0),
    'bathRoom': (0, 128, 0),
    'circulationArea': (0, 0, 128),
    'storageRoom': (128, 128, 0),
    'printerRoom': (128, 0, 128),
    'meetRoom': (0, 128, 128),
    'noRoom': (64, 0, 0),
    'none': (0, 64, 0),
    'kitchen': (0, 0, 64),
    'wardrobeRoom': (64, 64, 0),
    'quietRoom': (64, 0, 64),
    'custom': (0, 64, 64)
}
